version: '3.8'

services:
    alpine:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: symfony_docker
        restart: on-failure
        ports:
            - "8080:80"
        volumes:
            - ./conf/site.conf:/etc/nginx/http.d/default.conf
            - ./symfony_project:/var/www/html
        networks:
            - acpSymfony

    maildev:
        image: maildev/maildev
        container_name: maildev_docker
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - "8091:80"
        restart: always
        networks:
            - acpSymfony

    db:
        image: mariadb:10.11.2
        container_name: mariadb_docker
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'ChangeMeLater'
        networks:
            - acpSymfony

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker
        restart: always
        depends_on:
            - db
        ports:
            - "8090:80"
        environment:
            PMA_HOST: db
        networks:
            - acpSymfony

networks:
    acpSymfony:

volumes:
    db-data: